name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: awsgithubupload
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_TOKEN }}
          SOURCE_DIR: ./main
